permalink: /:year/:month/:title.html
pygments: true
paginate: 15
markdown: kramdown
exclude:
  - gem_env
  - install
  - README.markdown
domain: bhuztez.github.com
me: https://github.com/bhuztez
google-site-verification: amfPf2YNKMWjHmT-opHG7n-d8qMFKNPe_ABWnwvoMgg

